# Generated by Django 5.1 on 2025-12-14 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fundraisers", "0002_fundraiser_owner_pledge_supporter"),
    ]

    operations = [
        migrations.AddField(
            model_name="pledge",
            name="is_hidden_by_owner",
            field=models.BooleanField(default=False),
        ),
    ]
