# Generated by Django 5.1 on 2025-12-14 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fundraisers", "0003_pledge_is_hidden_by_owner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fundraiser",
            name="is_open",
            field=models.BooleanField(default=True),
        ),
    ]
